config/routes.rb
Rails.application.routes.draw do
  root to: 'session#new'

  get 'show_profile', to: 'profile#show'
  get 'edit_profile', to: 'profile#edit'
  put 'update_profile', to: 'profile#update'

  get 'dashboard', to: 'home#new', as: 'dashboard'

  resources :folders, only: [:create, :update, :get, :index, :destroy]
  get 'folders/:id/jobs', to: 'folders#jobs', as: 'folder_jobs'

  resources :jobs
  get 'job_list', to: 'jobs#jobs', as: 'job_list'
  get 'jobs/:id/runs', to: 'jobs#runs', as: 'job_runs'
  post 'jobs/:id/run_now', to: 'jobs#run_now', as: 'run_now'
  get 'tags', to: 'jobs#tags', as: 'tags'
  get 'parse_cron', to: 'jobs#parse_cron', as: 'parse_cron'

  # Get and update the status of context-sensitive help
  get 'help', to: 'help#show', as: 'show_help_status'
  post 'help', to: 'help#update', as: 'update_help_status'

  # Manage session
  post 'login', to: 'session#create', as: 'login'
  post 'logout', to: 'session#destroy', as: 'logout'

  # Home page stats
  get 'job_stats', to: 'home#job_stats', as: 'job_stats'
  get 'todays_stats', to: 'home#todays_stats', as: 'todays_stats'
  get 'upcoming_jobs', to: 'home#upcoming_jobs', as: 'upcoming_jobs'
  get 'recent_jobs', to: 'home#recent_jobs', as: 'recent_jobs'

  # Get the timezones that the BJR server understands
  get 'timezones', to: 'home#timezones', as: 'timezones'

  # Health check
  get 'health', to: 'health#index', as: 'health'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandler

  helper_method :current_user
  before_action :ensure_session

  def current_user
    if session[:token]
      @current_user = session[:token]
    else
      @current_user = nil
    end
  end

  def ensure_session
    redirect_to root_url, notice: I18n.t('common.session_timeout') if current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers::DateHelper

  #
  # Return the BJR server version
  #
  def server_version
    api = ApiClient.new
    api.server_version.object
  rescue
    flash.alert = I18n.t('common.errors.misconfigured')
    "(#{I18n.t('common.errors.unknown_version')})"
  end

  #
  # Get the version of BJR web
  #
  def web_version
    $version
  end

  #
  # Return an icon from ionicons for boolean value
  #
  def bool_icon(val)
    val ? '<span class="card-widget__icon2"><i class="icon-check text-success"></i></span>'.html_safe : '<span class="card-widget__icon2"><i class="icon-close text-danger"></i></span>'.html_safe
  end

  #
  # Try to coerce a value to a bool
  #
  def bool_val(val)
    [true, 'true', '1', 1, 'on'].include? val
  end

  #
  # Render a Bootstrap spinner
  #
  def spinner
    '<div class="spinner-border spinner-border-sm"></div>'.html_safe
  end

  #
  # Display a friendly help icon with a tool tip
  #
  def help_icon(tooltip_text)
    if session[:enable_help]
      "&nbsp;<i class=\"ion-help-circled\" title=\"#{tooltip_text}\" data-placement=\"auto\" data-toggle=\"tooltip\"></i>".html_safe
    else
      ''
    end
  end
end

app/views/application/_alerts.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-primary"><%= msg %></div>
<% end %>

app/views/application/_body.html.erb
<%= render 'preloader' %>
<div id="main-wrapper">
    <%= render 'nav_header' %>
    <%= render "header" %>
    <%= render "sidebar" %>
    <div class="content-body">
        <%= yield %>
    </div>
    <%= render 'footer' %>
</div>
<%= render "javascript" %>

app/views/application/_footer.html.erb
<div class="footer">
  <div class="copyright">
    <h5><p><%= t('.bjr_html') %></p></h5>
    <h6><p><%= t('.theme_html') %></p></h6>
  </div>
</div>

app/views/application/_hamburger.html.erb
<div class="nav-control">
    <div class="hamburger">
        <span class="toggle-icon"><i class="icon-menu"></i></span>
    </div>
</div>

app/views/application/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>BJR Web</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag     'application' %>

<%= favicon_link_tag 'favicon.png', type: 'image/png' %>

app/views/application/_header.html.erb
<div class="header">
    <div class="header-content clearfix">
        <%= render "hamburger" %>
        <%= render "menu_user" %>
    </div>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag 'js/custom.min', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'js/settings', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'js/gleek', 'data-turbolinks-track': 'reload' %>

app/views/application/_menu_user.html.erb
<div class="header-right">
  <ul class="clearfix">
    <li class="icons">
      <%= react_component('HelpWidget') %>
    </li>
    <li class="icons dropdown">
      <div class="c-pointer position-relative mt-4 mr-5" data-toggle="dropdown">
        <span class="card-widget__icon">
          <i class="icon-user"></i>
        </span>
      </div>
      <div class="drop-down dropdown-profile dropdown-menu">
        <div class="dropdown-content-body">
          <ul>
            <li>
              <%= link_to show_profile_url, method: :get do %>
                <i class="icon-user"></i>
                <span><%= t('.profile') %></span>
              <% end %>
            </li>
            <hr class="my-2"/>
            <li>
              <%= link_to logout_url, method: :post do %>
                <i class="icon-logout"></i>
                <span><%= t('.logout') %></span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/application/_nav_header.html.erb
<div class="nav-header">
  <div class="brand-logo">
    <a href="index.html">
      <b class="logo-abbr"><% image_tag 'logo.png' %></b>
      <span class="logo-compact"><%= image_tag 'logo-compact.png' %></span>
      <span class="brand-title"><%= image_tag 'logo-text.png' %></span>
    </a>
  </div>
</div>

app/views/application/_paginate.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy, 'class="page-link"') -%>
<%#                            -%><nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
<%#                            -%>  <ul class="pagination justify-content-end">
<% if pagy.prev                -%>    <li class="page-item prev"><%== link_to t('pagy.nav.prev'), jobs_path(page: pagy.prev), class: "page-link", method: :get %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link_to item.to_s, jobs_path(page: item), class: "page-link", method: :get %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link_to item.to_s, jobs_path(page: item), class: "page-link", method: :get %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>    <li class="page-item next"><%== link_to t('pagy.nav.next'), jobs_path(page: pagy.next), class: "page-link", method: :get %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
<%#                            -%>  </ul>
<%#                            -%></nav>

app/views/application/_preloader.html.erb
<div id="preloader">
  <div class="loader">
    <svg class="circular" viewBox="25 25 50 50">
      <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
    </svg>
  </div>
</div>

app/views/application/_search.html.erb
<div class="header-left">
    <div class="input-group icons">
        <div class="input-group-prepend">
            <span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i class="mdi mdi-magnify"></i></span>
        </div>
        <input type="search" class="form-control" placeholder="Search Dashboard" aria-label="Search Dashboard">
        <div class="drop-down   d-md-none">
            <form action="#">
                <input type="text" class="form-control" placeholder="Search">
            </form>
        </div>
    </div>
</div>

app/views/application/_sidebar.html.erb
<div class="nk-sidebar">
  <div class="nk-nav-scroll">
    <ul class="metismenu" id="menu">
      <li class="nav-label"><%= t('common.versions', server_version: server_version, web_version: web_version) %></li>
      <li>
        <%= link_to dashboard_url, method: :get, 'aria-expanded': false do %>
          <i class="icon-chart menu-icon"></i><span class="nav-text"><%= t('.dashboard') %></span>
        <% end %>
      </li>
      <li>
        <%= link_to jobs_url, method: :get, 'aria-expanded': false do %>
          <i class="icon-list menu-icon"></i><span class="nav-text"><%= t('.jobs') %></span>
        <% end %>
      </li>
      <li class="nav-label"><%= t('.folders') %></li>
      <%= react_component('FolderCollection') %>
    </ul>
  </div>
</div>